// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: indexer/blockfile.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash     string                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	UtxoData      map[string]*StringList `protobuf:"bytes,3,rep,name=utxo_data,json=utxoData,proto3" json:"utxo_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IncomeData    map[string]*StringList `protobuf:"bytes,4,rep,name=income_data,json=incomeData,proto3" json:"income_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SpendData     map[string]*StringList `protobuf:"bytes,5,rep,name=spend_data,json=spendData,proto3" json:"spend_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FBlock) Reset() {
	*x = FBlock{}
	mi := &file_indexer_blockfile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FBlock) ProtoMessage() {}

func (x *FBlock) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_blockfile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FBlock.ProtoReflect.Descriptor instead.
func (*FBlock) Descriptor() ([]byte, []int) {
	return file_indexer_blockfile_proto_rawDescGZIP(), []int{0}
}

func (x *FBlock) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FBlock) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *FBlock) GetUtxoData() map[string]*StringList {
	if x != nil {
		return x.UtxoData
	}
	return nil
}

func (x *FBlock) GetIncomeData() map[string]*StringList {
	if x != nil {
		return x.IncomeData
	}
	return nil
}

func (x *FBlock) GetSpendData() map[string]*StringList {
	if x != nil {
		return x.SpendData
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_indexer_blockfile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_blockfile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_indexer_blockfile_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_indexer_blockfile_proto protoreflect.FileDescriptor

const file_indexer_blockfile_proto_rawDesc = "" +
	"\n" +
	"\x17indexer/blockfile.proto\x12\aindexer\"\xf5\x03\n" +
	"\x06FBlock\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\tR\tblockHash\x12:\n" +
	"\tutxo_data\x18\x03 \x03(\v2\x1d.indexer.FBlock.UtxoDataEntryR\butxoData\x12@\n" +
	"\vincome_data\x18\x04 \x03(\v2\x1f.indexer.FBlock.IncomeDataEntryR\n" +
	"incomeData\x12=\n" +
	"\n" +
	"spend_data\x18\x05 \x03(\v2\x1e.indexer.FBlock.SpendDataEntryR\tspendData\x1aP\n" +
	"\rUtxoDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.indexer.StringListR\x05value:\x028\x01\x1aR\n" +
	"\x0fIncomeDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.indexer.StringListR\x05value:\x028\x01\x1aQ\n" +
	"\x0eSpendDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.indexer.StringListR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"StringList\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05itemsB5Z3srv/dev_project/metaid/utxo-indexer/indexer;indexerb\x06proto3"

var (
	file_indexer_blockfile_proto_rawDescOnce sync.Once
	file_indexer_blockfile_proto_rawDescData []byte
)

func file_indexer_blockfile_proto_rawDescGZIP() []byte {
	file_indexer_blockfile_proto_rawDescOnce.Do(func() {
		file_indexer_blockfile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_blockfile_proto_rawDesc), len(file_indexer_blockfile_proto_rawDesc)))
	})
	return file_indexer_blockfile_proto_rawDescData
}

var file_indexer_blockfile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_indexer_blockfile_proto_goTypes = []any{
	(*FBlock)(nil),     // 0: indexer.FBlock
	(*StringList)(nil), // 1: indexer.StringList
	nil,                // 2: indexer.FBlock.UtxoDataEntry
	nil,                // 3: indexer.FBlock.IncomeDataEntry
	nil,                // 4: indexer.FBlock.SpendDataEntry
}
var file_indexer_blockfile_proto_depIdxs = []int32{
	2, // 0: indexer.FBlock.utxo_data:type_name -> indexer.FBlock.UtxoDataEntry
	3, // 1: indexer.FBlock.income_data:type_name -> indexer.FBlock.IncomeDataEntry
	4, // 2: indexer.FBlock.spend_data:type_name -> indexer.FBlock.SpendDataEntry
	1, // 3: indexer.FBlock.UtxoDataEntry.value:type_name -> indexer.StringList
	1, // 4: indexer.FBlock.IncomeDataEntry.value:type_name -> indexer.StringList
	1, // 5: indexer.FBlock.SpendDataEntry.value:type_name -> indexer.StringList
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_indexer_blockfile_proto_init() }
func file_indexer_blockfile_proto_init() {
	if File_indexer_blockfile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_blockfile_proto_rawDesc), len(file_indexer_blockfile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indexer_blockfile_proto_goTypes,
		DependencyIndexes: file_indexer_blockfile_proto_depIdxs,
		MessageInfos:      file_indexer_blockfile_proto_msgTypes,
	}.Build()
	File_indexer_blockfile_proto = out.File
	file_indexer_blockfile_proto_goTypes = nil
	file_indexer_blockfile_proto_depIdxs = nil
}
